plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}" apply false
}

subprojects {
	apply plugin: 'java'
	apply plugin: 'maven-publish'

	version = rootProject.mod_version
	group = rootProject.maven_group
	base.archivesName = "${rootProject.name}-${project.name}"

	repositories {
		mavenCentral()
		maven {
			name = "Modrinth"
			url = "https://api.modrinth.com/maven"
		}
	}

	sourceSets {
		main {
			java.srcDir rootProject.file("common/src/main/java")
			resources.srcDir rootProject.file("common/src/main/resources")
		}
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 21
	}

	java {
		withSourcesJar()
		sourceCompatibility = JavaVersion.VERSION_21
		targetCompatibility = JavaVersion.VERSION_21
	}

	tasks.withType(Jar).configureEach {
		archiveBaseName.set("${rootProject.name}-${project.name}")

		from(rootProject.file("LICENSE")) {
			rename { "${it}_${rootProject.name}" }
		}
	}
}
